AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation frontend Demo
Resources:
	frontend:
		Type: 'AWS::Serverless::Function'
		Properties:
      CodeUri: ./frontend/index.html
Outputs:
	WebsiteURL:
		Value: !GetAtt
			- frontend
			- WebsiteURL
		Description: URL for Website Hosted on S3
	S3BucketSecureURL:
		Value: !Join
			- ''
			- - 'https://'
				- !GetAtt
					- frontend
					- frontendpipeline-lixuanyang
		Description: Name of S3 Bucket to hold website content
