version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.x
  build:
    commands:
      - aws cloudformation package --template-file lambdatemplate.yml
artifacts:
  files:
    - lambdatemplate.yml
